export const products = [
  { value: "Apple" },
  { value: "Apple (Autumn Crisp)" },
  { value: "Apple (Cripps Pink)" },
  { value: "Apple (Gala)" },
  { value: "Apple (Honeycrisp)" },
  { value: "Apple (McIntosh)" },
  { value: "Apple (Red Delicious)" },
  { value: "Apple (Scott)" },
  { value: "Apple (Yellow Delicious)" },
  { value: "Apricot" },
  { value: "Apricot (Manchurian)" },
  { value: "Artichoke" },
  { value: "Arugula" },
  { value: "Asparagus" },
  { value: "Aster" },
  { value: "Aster (Heath)" },
  { value: "Aster (New England)" },
  { value: "Aster (Smooth)" },
  { value: "Aster (Tufted White Prairie)" },
  { value: "Astilbe" },
  { value: "Astilbe (Burgundy Red)" },
  { value: "Astilbe (Visions in White)" },
  { value: "Aubergine" },
  { value: "Bacopa" },
  { value: "Bachelor's Button" },
  { value: "Balsam Fir" },
  { value: "Bamboo" },
  { value: "Banana Blossom" },
  { value: "Basil" },
  { value: "Bean (Bari - 5 Short Green)" },
  { value: "Bean (Black Valentine)" },
  { value: "Bean (Broad)" },
  { value: "Bean (Bush)" },
  { value: "Bean (Dry Shelling)" },
  { value: "Bean (Edamame)" },
  { value: "Bean (Fava)" },
  { value: "Bean (French)" },
  { value: "Bean (Green)" },
  { value: "Bean (Hyacinth)" },
  { value: "Bean (Ipsa - 1 Light Purple)" },
  { value: "Bean (Ipsa - 2 Small Green)" },
  { value: "Bean (Kidney)" },
  { value: "Bean (Lentil)" },
  { value: "Bean (Lima)" },
  { value: "Bean (Long)" },
  { value: "Bean (Moth)" },
  { value: "Bean (Navy)" },
  { value: "Bean (Pole)" },
  { value: "Bean (Provider)" },
  { value: "Bean (Runner)" },
  { value: "Bean (Snap)" },
  { value: "Bean (Soybean)" },
  { value: "Bean (String)" },
  { value: "Bean (Wax)" },
  { value: "Bean (Winged)" },
  { value: "Bean (Yardlong)" },
  { value: "Beardtongue (Hairy)" },
  { value: "Beet" },
  { value: "Beetroot" },
  { value: "Begonia" },
  { value: "Bell Pepper" },
  { value: "Bergamot" },
  { value: "Bilberry" },
  { value: "Birch (Cherry)" },
  { value: "Birch (Gray)" },
  { value: "Birch (Kenai Paper)" },
  { value: "Birch (Paper)" },
  { value: "Birch (Water)" },
  { value: "Birch (Yellow)" },
  { value: "Bitter Gourd" },
  { value: "Bitter Melon" },
  { value: "Black Ash" },
  { value: "Blackberry" },
  { value: "Black-Eyed Pea" },
  { value: "Black Spruce" },
  { value: "Black Walnut" },
  { value: "Blanket Flower" },
  { value: "Blue Flag Iris" },
  { value: "Blueberry" },
  { value: "Bluebell" },
  { value: "Bluegrass" },
  { value: "Blue Spruce" },
  { value: "Box Elder" },
  { value: "Boysenberry" },
  { value: "Broccoli" },
  { value: "Brussels Sprout" },
  { value: "Buckthorn (Common)" },
  { value: "Buckeye (Ohio)" },
  { value: "Borage" },
  { value: "Bottle Gourd" },
  { value: "Bottlebrush" },
  { value: "Bouncing Bet" },
  { value: "Broccoli" },
  { value: "Bromeliad" },
  { value: "Brown-Eyed Susan" },
  { value: "Buckwheat" },
  { value: "Budding Magnolia" },
  { value: "Bugleweed" },
  { value: "Bunchberry" },
  { value: "Burnet" },
  { value: "Bush Cranberry" },
  { value: "Buttercup" },
  { value: "Butternut" },
  { value: "Cabbage" },
  { value: "Caladium" },
  { value: "Calibrachoa" },
  { value: "California Poppy" },
  { value: "Calendula" },
  { value: "Canadian Anemone" },
  { value: "Canadian Columbine" },
  { value: "Canadian Goldenrod" },
  { value: "Candytuft" },
  { value: "Canna Lily" },
  { value: "Canterbury Bells" },
  { value: "Cantaloupe" },
  { value: "Cape Gooseberry" },
  { value: "Caraway" },
  { value: "Cardinal Flower" },
  { value: "Carnation" },
  { value: "Carolina Allspice" },
  { value: "Carrot" },
  { value: "Cascara Sagrada" },
  { value: "Catchfly" },
  { value: "Catmint" },
  { value: "Catnip" },
  { value: "Cauliflower" },
  { value: "Cedar" },
  { value: "Cedar (Northern White)" },
  { value: "Celandine Poppy" },
  { value: "Celery" },
  { value: "Centaurea" },
  { value: "Chamomile" },
  { value: "Chard (Swiss)" },
  { value: "Cherry" },
  { value: "Cherry (Evans)" },
  { value: "Cherry (Sour)" },
  { value: "Cherry (Sweet)" },
  { value: "Cherry Plum" },
  { value: "Chickpea" },
  { value: "Chicory" },
  { value: "Chili Pepper" },
  { value: "Chili Pepper (Charapita)" },
  { value: "Chili Pepper (Green)" },
  { value: "Chili Pepper (Hot)" },
  { value: "Chili Pepper (Naga)" },
  { value: "Chili Pepper (Red)" },
  { value: "Chinese Aster" },
  { value: "Chinese Cabbage" },
  { value: "Chinese Catalpa" },
  { value: "Chinese Chives" },
  { value: "Chinese Lantern" },
  { value: "Chinese Potato" },
  { value: "Chives" },
  { value: "Chokeberry" },
  { value: "Chokecherry" },
  { value: "Chrysanthemum" },
  { value: "Cilantro" },
  { value: "Cinnamon Vine" },
  { value: "Clarkia" },
  { value: "Clematis" },
  { value: "Clover" },
  { value: "Coleus" },
  { value: "Collards" },
  { value: "Columbine" },
  { value: "Comfrey" },
  { value: "Common Blue Violet" },
  { value: "Common Juniper" },
  { value: "Coneflower (Pale)" },
  { value: "Coneflower (Prairie)" },
  { value: "Coneflower (Purple)" },
  { value: "Coriander" },
  { value: "Corn" },
  { value: "Corn Plant" },
  { value: "Cornflower" },
  { value: "Cosmos" },
  { value: "Cottonwood" },
  { value: "Crabapple" },
  { value: "Crabapple (Siberian)" },
  { value: "Cranberry" },
  { value: "Cranberry (Highbush)" },
  { value: "Creeping Juniper" },
  { value: "Cress" },
  { value: "Crocus" },
  { value: "Cucumber" },
  { value: "Cucumber (Bush)" },
  { value: "Cucumber (Large)" },
  { value: "Cucumber (Round Deshi)" },
  { value: "Cucumber (Short)" },
  { value: "Cucumber (Socrates Variety)" },
  { value: "Currant" },
  { value: "Currant (Black)" },
  { value: "Currant (Missouri)" },
  { value: "Currant (Red)" },
  { value: "Cyclamen" },
  { value: "Daffodil" },
  { value: "Dahlia" },
  { value: "Daisy" },
  { value: "Daisy (African)" },
  { value: "Daisy (Florist's)" },
  { value: "Dandelion" },
  { value: "Daphne" },
  { value: "Daylily" },
  { value: "Delphinium" },
  { value: "Dianthus" },
  { value: "Dill" },
  { value: "Ditch Lily" },
  { value: "Dogwood (Alternate Leafed)" },
  { value: "Dogwood (Gray)" },
  { value: "Douglas-fir (Rocky Mountain)" },
  { value: "Dracena" },
  { value: "Drumstick" },
  { value: "Echinacea" },
  { value: "Eggplant" },
  { value: "Eggplant (Large Green)" },
  { value: "Eggplant (Large Purple)" },
  { value: "Eggplant (Long)" },
  { value: "Eggplant (Small Green Round)" },
  { value: "Eggplant (Small Purple Round)" },
  { value: "Elephant Foot Yam" },
  { value: "Endive" },
  { value: "Engelmann Spruce" },
  { value: "European Black Pine" },
  { value: "Evening Primrose" },
  { value: "Evergreen Candytuft" },
  { value: "Fennel" },
  { value: "Fern (Edible)" },
  { value: "Fern (Ostrich)" },
  { value: "Fescue" },
  { value: "Feverfew" },
  { value: "Fig" },
  { value: "Filbert" },
  { value: "Fir (Alpine)" },
  { value: "Fir (Balsam)" },
  { value: "Flax (Blue)" },
  { value: "Forget-Me-Not" },
  { value: "Foxglove" },
  { value: "Foxtail Lily" },
  { value: "Fragrant Pear" },
  { value: "French Marigold" },
  { value: "Fuchsia" },
  { value: "Gaillardia" },
  { value: "Gardenia" },
  { value: "Garlic" },
  { value: "Geranium" },
  { value: "Geranium (Spotted)" },
  { value: "Germander" },
  { value: "Giant Hyssop" },
  { value: "Ginger" },
  { value: "Gladiolus" },
  { value: "Globe Thistle" },
  { value: "Gloriosa Daisy" },
  { value: "Goat's Beard" },
  { value: "Goji Berry" },
  { value: "Golden Alexander" },
  { value: "Golden Bean" },
  { value: "Goldenrod" },
  { value: "Goldenrod (Canada)" },
  { value: "Goldenrod (Gray)" },
  { value: "Goldenrod (Zigzag)" },
  { value: "Gooseberry" },
  { value: "Grape" },
  { value: "Grape (Bluebell)" },
  { value: "Grape (Frontenac)" },
  { value: "Grape (Marechael Foch)" },
  { value: "Grape (Valiant)" },
  { value: "Grass (Canada Wild Rye)" },
  { value: "Grass (Little Bluestem)" },
  { value: "Grass (Prairie Dropseed)" },
  { value: "Green Amaranth" },
  { value: "Green Bean" },
  { value: "Green Pepper" },
  { value: "Ground Cherry" },
  { value: "Groundnut" },
  { value: "Guava" },
  { value: "Hackberry" },
  { value: "Hairy Vetch" },
  { value: "Hardtack" },
  { value: "Hardy Garden Mum" },
  { value: "Haskap" },
  { value: "Hawthorn (Arnold)" },
  { value: "Hazelnut" },
  { value: "Heath" },
  { value: "Hellebore (White)" },
  { value: "Hemerocallis" },
  { value: "Hibiscus" },
  { value: "Highbush Cranberry" },
  { value: "Holly" },
  { value: "Hollyhock" },
  { value: "Honesty" },
  { value: "Honeyberry" },
  { value: "Honeysuckle" },
  { value: "Hops" },
  { value: "Hornbeam (American)" },
  { value: "Horseradish" },
  { value: "Hosta" },
  { value: "Houseleek" },
  { value: "Huckleberry" },
  { value: "Hyacinth" },
  { value: "Iceland Poppy" },
  { value: "Impatiens" },
  { value: "Indian Paintbrush" },
  { value: "Indian Pea" },
  { value: "Indian Pipe" },
  { value: "Indian Thistle" },
  { value: "Iris" },
  { value: "Iris (Blue Flag)" },
  { value: "Iris (Siberian)" },
  { value: "Italian Parsley" },
  { value: "Ivy Gourd" },
  { value: "Jack Pine" },
  { value: "Jackfruit" },
  { value: "Jerusalem Artichoke" },
  { value: "Jicama" },
  { value: "Jonquil" },
  { value: "Juniper (Chinese)" },
  { value: "Juniper (Common)" },
  { value: "Juniper (Creeping)" },
  { value: "Juniper (Eastern)" },
  { value: "Juniper (Rocky Mountain)" },
  { value: "Juniper (Savin)" },
  { value: "Jute Leaves" },
  { value: "Kale" },
  { value: "Kale (Red Russian)" },
  { value: "Kale (Scotch)" },
  { value: "Kentucky Bluegrass" },
  { value: "Kentucky Coffee Tree" },
  { value: "Kiwiberry" },
  { value: "Kohlrabi" },
  { value: "Kumquat" },
  { value: "Lady's Mantle" },
  { value: "Lamb's Quarters" },
  { value: "Lamb's Ear" },
  { value: "Lantana" },
  { value: "Larch (Eastern)" },
  { value: "Larkspur" },
  { value: "Lavender" },
  { value: "Leek" },
  { value: "Lemon" },
  { value: "Lemon Balm" },
  { value: "Lemon Verbena" },
  { value: "Lettuce" },
  { value: "Lettuce (Buttercrunch)" },
  { value: "Lettuce (Leaf)" },
  { value: "Lettuce (Green Oakleaf)" },
  { value: "Lettuce (Red Oakleaf)" },
  { value: "Lettuce (Romaine)" },
  { value: "Lettuce (Black-Seeded Simpson)" },
  { value: "Lilac" },
  { value: "Lilac (Common)" },
  { value: "Lily" },
  { value: "Lily (Asiatic)" },
  { value: "Lily (Calla)" },
  { value: "Lily (Candelabra)" },
  { value: "Lily (Casa Blanca)" },
  { value: "Lily (Day)" },
  { value: "Lily (Easter)" },
  { value: "Lily (Tiger)" },
  { value: "Lily of the Valley" },
  { value: "Lime" },
  { value: "Limber Pine" },
  { value: "Lobelia" },
  { value: "Lodgepole Pine" },
  { value: "Loosestrife (Purple)" },
  { value: "Lungwort (Tall)" },
  { value: "Lupin" },
  { value: "Magnolia (Royal Star)" },
  { value: "Magnolia ('Betty')" },
  { value: "Malabar Spinach (Green)" },
  { value: "Malabar Spinach (Red)" },
  { value: "Mallow (American)" },
  { value: "Mandarin Orange" },
  { value: "Mango" },
  { value: "Manitoba Maple" },
  { value: "Maple (Manitoba)" },
  { value: "Maple (Paperbark)" },
  { value: "Maple (Red)" },
  { value: "Maple (Silver)" },
  { value: "Maple (Sugar)" },
  { value: "Marigold" },
  { value: "Marigold (African)" },
  { value: "Marigold (French)" },
  { value: "Marjoram" },
  { value: "Masterwort" },
  { value: "Matilija Poppy" },
  { value: "Meadow Rue" },
  { value: "Melilot" },
  { value: "Melissa" },
  { value: "Melon" },
  { value: "Mexican Hat" },
  { value: "Microgreens" },
  { value: "Migratory Milkweed" },
  { value: "Milfoil" },
  { value: "Milkweed (Common)" },
  { value: "Mint" },
  { value: "Mint (Dotted)" },
  { value: "Mint (Mountain)" },
  { value: "Missouri Currant" },
  { value: "Monarda" },
  { value: "Money Plant" },
  { value: "Monkshood" },
  { value: "Moonflower" },
  { value: "Morning Glory" },
  { value: "Moss" },
  { value: "Mountain Ash (European)" },
  { value: "Mountain Paper Birch" },
  { value: "Mugwort" },
  { value: "Mulberry" },
  { value: "Mullein" },
  { value: "Mushroom" },
  { value: "Mushroom (Button)" },
  { value: "Mushroom (Morel)" },
  { value: "Mustard" },
  { value: "Mustard Greens" },
  { value: "Myrrh" },
  { value: "Narcissus" },
  { value: "Nasturtium" },
  { value: "Native Cranberry" },
  { value: "Nectarine" },
  { value: "Nemophila" },
  { value: "Nepeta" },
  { value: "New York Ironweed" },
  { value: "Nodding Onion" },
  { value: "Norway Spruce" },
  { value: "Oak (Bur)" },
  { value: "Oak (Northern Pin)" },
  { value: "Oak (Scarlet)" },
  { value: "Okra" },
  { value: "Okra (Lady Finger)" },
  { value: "Old Man's Beard" },
  { value: "Oleander" },
  { value: "Olive" },
  { value: "Onion" },
  { value: "Onion (Green)" },
  { value: "Onion (Nodding Prairie)" },
  { value: "Onion (Spring)" },
  { value: "Orach" },
  { value: "Oregon Grape" },
  { value: "Oregano" },
  { value: "Ornamental Cabbage" },
  { value: "Ornamental Grass" },
  { value: "Ornamental Pepper" },
  { value: "Ornamental Rhubarb" },
  { value: "Osteospermum" },
  { value: "Oxeye Daisy" },
  { value: "Pacific Dogwood" },
  { value: "Painted Daisy" },
  { value: "Pansy" },
  { value: "Papaya" },
  { value: "Paper Birch" },
  { value: "Paperbark Maple" },
  { value: "Parsley" },
  { value: "Parsnip" },
  { value: "Partridgeberry" },
  { value: "Pasqueflower" },
  { value: "Passion Flower" },
  { value: "Pea" },
  { value: "Pea (Dried)" },
  { value: "Pea (Edible-Podded)" },
  { value: "Pea (Garden)" },
  { value: "Pea (Indian)" },
  { value: "Pea (Oregon Sugar Pod)" },
  { value: "Pea (Shelling)" },
  { value: "Pea (Sugar Snap)" },
  { value: "Pea (Sweet)" },
  { value: "Peach" },
  { value: "Pear" },
  { value: "Pear (Early Gold)" },
  { value: "Pear (John)" },
  { value: "Pear (Spice)" },
  { value: "Pearly Everlasting" },
  { value: "Pecan" },
  { value: "Pelargonium" },
  { value: "Penstemon" },
  { value: "Peony" },
  { value: "Peony (Pink)" },
  { value: "Pepper (Bell)" },
  { value: "Peppermint" },
  { value: "Perennial Pea" },
  { value: "Periwinkle" },
  { value: "Persian Buttercup" },
  { value: "Petunia" },
  { value: "Phlox" },
  { value: "Phlox (Red Flame)" },
  { value: "Phlox (White Eye Flame)" },
  { value: "Pickerelweed" },
  { value: "Pigeon Pea" },
  { value: "Pine (Eastern White)" },
  { value: "Pine (European Black)" },
  { value: "Pine (Jack)" },
  { value: "Pine (Limber)" },
  { value: "Pine (Lodgepole)" },
  { value: "Pine (Mountain)" },
  { value: "Pine (Ponderosa)" },
  { value: "Pine (Red)" },
  { value: "Pine (Scots)" },
  { value: "Pine (Shore)" },
  { value: "Pine (Sitka)" },
  { value: "Pine (Western White)" },
  { value: "Pine (Whitebark)" },
  { value: "Pineberry" },
  { value: "Pink" },
  { value: "Pink (Dianthus Barbatus)" },
  { value: "Pink (Dianthus Japonicus)" },
  { value: "Pink (Dianthus Superbus)" },
  { value: "Pincherry" },
  { value: "Pinks" },
  { value: "Pitch Pine" },
  { value: "Plantain" },
  { value: "Plum" },
  { value: "Plum (Cherry)" },
  { value: "Plum (Manor)" },
  { value: "Plum (Pembina)" },
  { value: "Podophyllum" },
  { value: "Pointed Gourd" },
  { value: "Poinsettia" },
  { value: "Pole Bean" },
  { value: "Ponderosa Pine" },
  { value: "Poppy" },
  { value: "Potato" },
  { value: "Potato (Chinese)" },
  { value: "Potato (Sweet)" },
  { value: "Pot Marigold" },
  { value: "Potentilla" },
  { value: "Prayer Plant" },
  { value: "Prairie Coneflower" },
  { value: "Prairie Crocus" },
  { value: "Prairie Dropseed" },
  { value: "Prairie Smoke" },
  { value: "Prickly Pear" },
  { value: "Primrose" },
  { value: "Prince's Feather" },
  { value: "Privet" },
  { value: "Prune" },
  { value: "Pumpkin" },
  { value: "Pumpkin (Deshi Sweet)" },
  { value: "Pussy Willow" },
  { value: "Pyracantha" },
  { value: "Queen Anne's Lace" },
  { value: "Quince" },
  { value: "Radish" },
  { value: "Radish (Daikon)" },
  { value: "Radish (Field)" },
  { value: "Radish (White)" },
  { value: "Raspberry" },
  { value: "Red Amaranth" },
  { value: "Red Clover" },
  { value: "Red Hot Poker" },
  { value: "Red Maple" },
  { value: "Red Osier Dogwood" },
  { value: "Red Pine" },
  { value: "Red Spruce" },
  { value: "Red Valerian" },
  { value: "Rhododendron" },
  { value: "Rhubarb" },
  { value: "Rhubarb (Homesteader)" },
  { value: "Rhubarb (Macdonald)" },
  { value: "Rhubarb (Strawberry Red)" },
  { value: "Rhubarb (Victoria Red)" },
  { value: "Ribbed Gourd" },
  { value: "Ridge Gourd" },
  { value: "Rock Cress" },
  { value: "Rocket" },
  { value: "Rocky Mountain Douglas-fir" },
  { value: "Rocky Mountain Juniper" },
  { value: "Rose" },
  { value: "Rosemary" },
  { value: "Rudbeckia" },
  { value: "Runner Bean" },
  { value: "Russian Sage" },
  { value: "Rutabaga" },
  { value: "Sage" },
  { value: "Sagebrush" },
  { value: "Salal" },
  { value: "Salvia" },
  { value: "Sand Cherry" },
  { value: "Sand Verbena" },
  { value: "Santolina" },
  { value: "Saskatoon" },
  { value: "Savin Juniper" },
  { value: "Saxifrage" },
  { value: "Scarlet Beebalm" },
  { value: "Scarlet Runner Bean" },
  { value: "Scarlet Sage" },
  { value: "Schizachyrium" },
  { value: "Scots Pine" },
  { value: "Sea Holly" },
  { value: "Sea Pink" },
  { value: "Sedge" },
  { value: "Sedum" },
  { value: "Sempervivum" },
  { value: "September Ruby Apple" },
  { value: "Serbian Spruce" },
  { value: "Serviceberry (Downy)" },
  { value: "Serviceberry (Smooth)" },
  { value: "Shallot" },
  { value: "Shining Arnica" },
  { value: "Shore Pine" },
  { value: "Sideoats Grama" },
  { value: "Silene" },
  { value: "Silver Birch" },
  { value: "Silver Maple" },
  { value: "Silverweed" },
  { value: "Sitka Spruce" },
  { value: "Skimmia" },
  { value: "Smoke Tree" },
  { value: "Smooth Aster" },
  { value: "Smooth Serviceberry" },
  { value: "Snake Gourd" },
  { value: "Sneezeweed" },
  { value: "Snowberry" },
  { value: "Snowdrop" },
  { value: "Soapwort" },
  { value: "Solidago" },
  { value: "Sorrel" },
  { value: "Sour Cherry" },
  { value: "Southernwood" },
  { value: "Soybean" },
  { value: "Speedwell" },
  { value: "Spider Flower" },
  { value: "Spiny Amaranth" },
  { value: "Spiny Gourd" },
  { value: "Spinach" },
  { value: "Spinach (Arum)" },
  { value: "Spinach (Ceylon)" },
  { value: "Spinach (Indian)" },
  { value: "Spinach (Malabar)" },
  { value: "Spinach (New Zealand)" },
  { value: "Spinach (Palang)" },
  { value: "Spinach (Perennial)" },
  { value: "Spinach (Strawberry)" },
  { value: "Sponge Gourd" },
  { value: "Spotted Geranium" },
  { value: "Spring Onion" },
  { value: "Spruce (Black)" },
  { value: "Spruce (Colorado)" },
  { value: "Spruce (Engelmann)" },
  { value: "Spruce (Norway)" },
  { value: "Spruce (Red)" },
  { value: "Spruce (Serbian)" },
  { value: "Spruce (Sitka)" },
  { value: "Spruce (White)" },
  { value: "Squash" },
  { value: "Squash (Summer)" },
  { value: "Squash (Winter)" },
  { value: "Squirrel Corn" },
  { value: "St. John's Wort" },
  { value: "Staghorn Sumac" },
  { value: "Statice" },
  { value: "Stock" },
  { value: "Stonecrop" },
  { value: "Strawberry" },
  { value: "Strawberry (Wild)" },
  { value: "String Bean" },
  { value: "Sugar Maple" },
  { value: "Sugar Snap Pea" },
  { value: "Sumac" },
  { value: "Sunflower" },
  { value: "Sweet Alyssum" },
  { value: "Sweet Basil" },
  { value: "Sweet Corn" },
  { value: "Sweet Pea" },
  { value: "Sweet Pepper" },
  { value: "Sweet Potato" },
  { value: "Sweet William" },
  { value: "Sweet Woodruff" },
  { value: "Swiss Chard" },
  { value: "Switchgrass" },
  { value: "Sylheti Bean (Green - Flat)" },
  { value: "Symphyotrichum" },
  { value: "Tamarack" },
  { value: "Tansy" },
  { value: "Taro" },
  { value: "Taro (Arum Root)" },
  { value: "Taro Stem Root" },
  { value: "Thistle" },
  { value: "Thyme" },
  { value: "Tickseed" },
  { value: "Tinda" },
  { value: "Tomatillo" },
  { value: "Tomato" },
  { value: "Tomato (Cherry)" },
  { value: "Torch Lily" },
  { value: "Trillium" },
  { value: "Trollius" },
  { value: "Trumpet Vine" },
  { value: "Tulip" },
  { value: "Tuberose" },
  { value: "Turnip" },
  { value: "Turnip (Field)" },
  { value: "Turnip (White)" },
  { value: "Turtlehead" },
  { value: "Twinflower" },
  { value: "Twisted Stock" },
  { value: "Umbrella Plant" },
  { value: "Upright Sedum" },
  { value: "Urad Dal" },
  { value: "Valiant Grape" },
  { value: "Vancouveria" },
  { value: "Variegated Liriope" },
  { value: "Vegetable Marrow" },
  { value: "Verbena" },
  { value: "Verbena (Hoary)" },
  { value: "Veronica" },
  { value: "Vetch" },
  { value: "Viburnum" },
  { value: "Vinca" },
  { value: "Violet" },
  { value: "Violet (Early Blue)" },
  { value: "Virgin's Bower" },
  { value: "Virginia Creeper" },
  { value: "Virginia Waterleaf" },
  { value: "Vista" },
  { value: "Vitis" },
  { value: "Volutpat" },
  { value: "Wake-Robin" },
  { value: "Wall Cress" },
  { value: "Wallflower" },
  { value: "Walnut (Black)" },
  { value: "Water Amaranth" },
  { value: "Water Birch" },
  { value: "Water Chestnut" },
  { value: "Water Hyacinth" },
  { value: "Water Lily" },
  { value: "Water Spinach" },
  { value: "Watercress" },
  { value: "Watermelon" },
  { value: "Wax Bean" },
  { value: "Wax Gourd" },
  { value: "Weigela" },
  { value: "Western White Pine" },
  { value: "White Ash" },
  { value: "White Beardtongue" },
  { value: "White Spruce" },
  { value: "Whitebark Pine" },
  { value: "Wild Bergamot" },
  { value: "Wild Ginger" },
  { value: "Wild Strawberry" },
  { value: "Wild Yam" },
  { value: "Willow" },
  { value: "Willow (Bullata Crack)" },
  { value: "Willow (Pussy)" },
  { value: "Windflower" },
  { value: "Wine Grape" },
  { value: "Winter Aconite" },
  { value: "Winter Cheek Apple" },
  { value: "Wintergreen" },
  { value: "Winter Squash" },
  { value: "Wisteria" },
  { value: "Witch Hazel" },
  { value: "Wolfsbane" },
  { value: "Woodland Strawberry" },
  { value: "Wormwood" },
  { value: "Yarrow" },
  { value: "Yardlong Bean" },
  { value: "Yellow Birch" },
  { value: "Yellow Coneflower" },
  { value: "Yellow Jessamine" },
  { value: "Yellow Pear Tomato" },
  { value: "Yew" },
  { value: "Youth-on-Age" },
  { value: "Zinnia" },
  { value: "Zucchini" },
  { value: "Other" },
];
